package applesignin

type ValidationRequest struct {
	// ClientID is the "Services ID" value that you get when navigating to your "sign in with Apple"-enabled service ID
	ClientID string `json:"client_id"`

	// ClientSecret is secret generated as a JSON Web Token that uses the secret key generated by the WWDR portal.
	// It can also be generated using the GenerateClientSecret function provided in this package
	ClientSecret string `json:"client_secret"`

	// Code is the authorization code received from your application’s user agent.
	// The code is single use only and valid for five minutes.
	Code string `json:"code"`

	// RefreshToken is the refresh token received during the authorization request. Only required when validating
	// refresh token
	RefreshToken string `json:"refresh_token"`

	// RedirectURI is the destination URI the code was originally sent to.
	// Redirect URLs must be registered with Apple. You can register up to 10. Apple will throw an error with IP address
	// URLs on the authorization screen, and will not let you add localhost in the developer portal.
	RedirectURI string `json:"redirect_uri"`

	// GrantType determines how the client interacts with the server. For authorization code validation,
	// use "authorization_code". For refresh token validation requests, use "refresh_token".
	GrantType string `json:"grant_type"`
}
